# Module One Assignment

For the module one assignment you are not required to produce or submit any coding samples. This Notebook is provided with some sample exploratory data analysis (EDA) commands to help learn more about your data. If you would like to explore the data in another tool, just download the sample data file to your local machine for further exploratory analysis.

### Data Source Information
The sourcing information for the data sets can be found in the `README.md` file within the data folder.

To use this sample EDA script to explore your selected data set, replace the `data/sample_use_only/stars.csv` with the reference to your selected data from the list below:

- `data/business_data.csv`
- `data/Crime_Data_from_2020_to_Present.csv`
- `data/NCHS_-_Leading_Causes_of_Death__United_States.csv`
- `data/Provisional_COVID-19_Deaths_by_Sex_and_Age.csv`
- `data/titanic_raw.csv`

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>To Begin:</i></b> replace the <mark>data/sample_use_only/stars.csv</mark> sample data path with the path to your selected data set.</span>
</div>

In [1]:
reference_file = "data/NCHS_-_Leading_Causes_of_Death__United_States.csv"

## Installing Required Packages

In [2]:
import sys
!{sys.executable} -m pip install --upgrade pip setuptools
!{sys.executable} -m pip install -r requirements.txt

Requirement already satisfied: pip in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (26.0.1)
Requirement already satisfied: setuptools in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (70.3.0)
Collecting setuptools
  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 70.3.0
    Uninstalling setuptools-70.3.0:
      Successfully uninstalled setuptools-70.3.0
Successfully installed setuptools-82.0.1
Requirement already satisfied: ydata-profiling>=4.17.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.13.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.2.6)
Requirement already satisfied: minify-html>=0.15.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.33.1)
Requirement already satisfied: tqdm<5,>=4.66.3 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.62.1)
Requirement already satisfied: PyWavelets in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from imagehash==4.3.2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.8.0)
Requirement already satisfied: pillow in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from imagehash==4.3.2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (12.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from numba<0.63,>=0.60->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from phik<0.13,>=0.12.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pydantic<3,>=2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pydantic<3,>=2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.46.3)
Requirement already satisfied: typing-extensions>=4.14.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pydantic<3,>=2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pydantic<3,>=2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from requests<3,>=2.32.0->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from requests<3,>=2.32.0->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from requests<3,>=2.32.0->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from requests<3,>=2.32.0->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2026.4.22)
Requirement already satisfied: patsy>=0.5.6 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.4.2)
Requirement already satisfied: puremagic in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.30)
Requirement already satisfied: six>=1.5 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.17.0)

In [3]:
!pip install --upgrade pip setuptools
!pip install -r requirements.txt

Requirement already satisfied: pip in /home/dukeph0/anaconda3/lib/python3.13/site-packages (26.0.1)
Requirement already satisfied: setuptools in /home/dukeph0/anaconda3/lib/python3.13/site-packages (82.0.1)
Requirement already satisfied: ydata-profiling>=4.17.0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from -r requirements.txt (line 1)) (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.11.7)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: minify-html>=0.15.0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.14.4)
Requirement already satisfied: typeguard<5,>=4 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.61.0)
Requirement already satisfied: PyWavelets in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from imagehash==4.3.2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.8.0)
Requirement already satisfied: pillow in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from imagehash==4.3.2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from numba<0.63,>=0.60->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from phik<0.13,>=0.12.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: pydantic-core==2.33.2 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2026.4.22)
Requirement already satisfied: patsy>=0.5.6 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (24.3.0)
Requirement already satisfied: networkx>=2.4 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (3.4.2)
Requirement already satisfied: puremagic in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: six>=1.5 in /home/dukeph0/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling>=4.17.0->-r requirements.txt (line 1)) (1.17.0)

## Import the Required Packages

In [4]:
import sys
import os
# Forcefully add the site-packages of the current python environment to the path
env_path = os.path.dirname(sys.executable)
site_packages = os.path.join(env_path, 'lib', f'python{sys.version_info.major}.{sys.version_info.minor}', 'site-packages')
if site_packages not in sys.path:
    sys.path.insert(0, site_packages)
    print(f"Forcefully added to path: {site_packages}")

Forcefully added to path: /home/dukeph0/anaconda3/envs/ai_titan/bin/lib/python3.10/site-packages

In [2]:
import pandas as pd
from ydata_profiling import ProfileReport

/tmp/ipykernel_32337/2829373970.py:2: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

## Methods and Attributes between Series and DataFrames

- A **DataFrame** is a 2-dimensional table consisting of rows and columns
- Pandas uses a `NaN` designation for cells that have a missing value. NaN is short for "not a number" which will produce `NaN` values with most operations run against them.
- Like with **Series**, Pandas assigns an index position/label to each **DataFrame** row.
- The `hasnans` attribute exists only in a **Series**. The `columns` attribute exists only on a **DataFrame**.
- Some methods/attributes will return different types of data.
- The `info` method returns a summary of the pandas object.

## Loading the Data
After you have selected your data set that wish to wrangle, replace the reference file path, then run the block.

In [3]:
raw_data = pd.read_csv(reference_file)
raw_data

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
0,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,United States,169936,49.4
1,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alabama,2703,53.8
2,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alaska,436,63.7
3,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arizona,4184,56.2
4,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arkansas,1625,51.8
...,...,...,...,...,...,...
10863,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Virginia,1035,16.9
10864,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,278,5.2
10865,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,West Virginia,345,16.4
10866,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Wisconsin,677,11.9
10867,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Wyoming,30,6.8

### Pandas
Pandas is usually very good at figuring out which options to use based on the input data, so we often won't need to add arguments to the call; however, there are many options available should we need them, some of which include the following:

| Parameter | Purpose |
| --- | --- |
| `sep` | Specifies the delimiter |
| `header` | Row number where the column names are located; the default option has `pandas` infer whether they are present |
| `names` | List of column names to use as the header |
| `index_col` | Column to use as the index |
| `usecols` | Specifies which columns to read in |
| `dtype` | Specifies data types for the columns | 
| `converters` | Specifies functions for converting data in certain columns |
| `skiprows` | Rows to skip |
| `nrows` | Number of rows to read at a time (combine with `skiprows` to read a file bit by bit) |
| `parse_dates` | Automatically parse columns containing dates into datetime objects |
| `chunksize` | For reading the file in chunks |
| `compression` | For reading in compressed files without extracting beforehand |
| `encoding` | Specifies the file encoding |

## Examining the Data

### Shape
For a **DataFrame**, the `shape` attribute returns a tuple with two elements: the first element represents the number of rows, and the second element represents the number of columns. For example, if a DataFrame has 10 rows and 5 columns, the shape attribute will return (10, 5).

For a **Series**, the `shape` attribute returns a tuple with one element: the number of elements in the Series. For example, if a Series has 7 elements, the shape attribute will return (7,).

In [5]:
raw_data.shape

(10868, 6)

### Head
The `head()` function in pandas is used to display the first n rows of a DataFrame or Series. If no argument is passed, it defaults to showing the first 5 rows. It's a useful tool for quickly inspecting the data and understanding its structure, especially when dealing with large datasets.

In [6]:
raw_data.head(10)

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
0,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,United States,169936,49.4
1,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alabama,2703,53.8
2,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alaska,436,63.7
3,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arizona,4184,56.2
4,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arkansas,1625,51.8
5,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,California,13840,33.2
6,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Colorado,3037,53.6
7,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Connecticut,2078,53.2
8,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Delaware,608,61.9
9,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,District of Columbia,427,61.0

### Tail
The `tail()` method in pandas is used to retrieve the last n rows of a DataFrame or Series. By default, it returns the last 5 rows, but this number can be customized by passing an integer argument n to the method.

In [7]:
raw_data.tail(10)

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
10858,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Tennessee,675,12.3
10859,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Texas,1669,10.3
10860,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,United States,35525,13.0
10861,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Utah,135,9.1
10862,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Vermont,56,9.2
10863,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Virginia,1035,16.9
10864,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Washington,278,5.2
10865,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,West Virginia,345,16.4
10866,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Wisconsin,677,11.9
10867,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Wyoming,30,6.8

### Info
The DataFrames object has a method called `info()`, that gives you more information about the data set which can help pinpoint missing values and wrong data types.

In [8]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10868 entries, 0 to 10867
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     10868 non-null  int64
 1   113 Cause Name           10868 non-null  object
 2   Cause Name               10868 non-null  object
 3   State                    10868 non-null  object
 4   Deaths                   10868 non-null  int64
 5   Age-adjusted Death Rate  10868 non-null  float64
dtypes: float64(1), int64(2), object(3)
memory usage: 509.6+ KB


### Columns
Columns in a Pandas DataFrame are similar to columns in a spreadsheet or SQL table. Each column is a Series object, which is a one-dimensional array with an associated index. Data types within a column must be homogenous.

- **Selecting a column:** Columns can be selected using bracket notation `df['column_name']` or dot notation `df.column_name`. The former is more versatile, especially when column names contain spaces or special characters.
- **Adding a column:** New columns can be added by assignment: `df['new_column'] = values`.
- **Deleting a column:** Columns can be deleted using `del df['column_name']` or `df.drop('column_name', axis=1, inplace=True)`.
- **Renaming columns:** Columns can be renamed using `df.rename(columns={'old_name': 'new_name'}, inplace=True)`.
- **Getting column names:** The column names can be accessed as an **Index** object using `df.columns`.
- **Iterating through columns:** You can iterate through the columns using a for loop: `for column in 'df.columns`.
- **Data types of columns:** Each column can have a different data type. The data type of a column can be accessed using `df['column_name'].dtype`. Common data types include int, float, object, datetime, and bool. 
- **Applying functions to columns:** Functions can be applied to columns using the `apply()` method.
- **Calculating between columns:** New columns can be calculated using basic arithmetic operators. For example `df['new_column'] = df['column_1'] + df['column_2']`.

In [9]:
raw_data.columns

Index(['Year', '113 Cause Name', 'Cause Name', 'State', 'Deaths',
       'Age-adjusted Death Rate'],
      dtype='object')

### dtypes
The `dtypes` property returns data type of each column in the DataFrame. You will note here that you previous saw the datatypes by column listed in the output of the .info() method.

In [10]:
raw_data.dtypes

Year                         int64
113 Cause Name              object
Cause Name                  object
State                       object
Deaths                       int64
Age-adjusted Death Rate    float64
dtype: object

### Describe
The `describe()` method returns description of the data in the DataFrame.

If the DataFrame contains numerical data, the description contains these information for each column:

    count - The number of not-empty values.
    mean - The average (mean) value.
    std - The standard deviation.
    min - the minimum value.
    25% - The 25% percentile*.
    50% - The 50% percentile*.
    75% - The 75% percentile*.
    max - the maximum value.

***Percentile meaning:** how many of the values are less than the given percentile.*

In [11]:
raw_data.describe()

               Year        Deaths  Age-adjusted Death Rate
count  10868.000000  1.086800e+04             10868.000000
mean    2008.000000  1.545991e+04               127.563894
std        5.477478  1.128760e+05               223.639771
min     1999.000000  2.100000e+01                 2.600000
25%     2003.000000  6.120000e+02                19.200000
50%     2008.000000  1.718500e+03                35.900000
75%     2013.000000  5.756500e+03               151.725000
max     2017.000000  2.813503e+06              1087.300000

### Data Profiling
Data quality profiling and exploratory data analysis are crucial steps in the process of Data Science and Machine Learning development. **YData-profiling** is a leading tool in the data understanding step of the data science workflow as a pioneering Python package.

`ydata-profiling` is a leading package for data profiling, that automates and standardizes the generation of detailed reports, complete with statistics and visualizations. The significance of the package lies in how it streamlines the process of understanding and preparing data for analysis in a single line of code!

In [4]:
profile = ProfileReport(raw_data, title="Sample Profile Report") 
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 6/6 [00:00<00:00, 196.46it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]